/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC20 } from "./ERC20";
export type { IERC20 } from "./IERC20";
export type { IPrestige } from "./IPrestige";
export type { TVKPrestige } from "./TVKPrestige";
export type { TVKTest } from "./TVKTest";

export { ERC20__factory } from "./factories/ERC20__factory";
export { IERC20__factory } from "./factories/IERC20__factory";
export { IPrestige__factory } from "./factories/IPrestige__factory";
export { TVKPrestige__factory } from "./factories/TVKPrestige__factory";
export { TVKTest__factory } from "./factories/TVKTest__factory";
